// This file is auto-generated by `supabase gen types typescript`
// Run: npx supabase gen types typescript --project-id YOUR_PROJECT_ID > src/lib/supabase/types.ts
// For now, this placeholder allows the app to compile.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          display_name: string
          role: 'owner' | 'staff' | 'student'
          is_active: boolean
          linked_student_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          display_name: string
          role: 'owner' | 'staff' | 'student'
          is_active?: boolean
          linked_student_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>
      }
      app_settings: {
        Row: {
          id: string
          inst_name: string
          inst_address: string | null
          inst_phone: string | null
          admin_email: string | null
          wa_template: string | null
          wa_template_fee_reminder: string | null
          reminder_days: number
          reminder_hour: number
          created_at: string
          updated_at: string
        }
        Insert: Partial<Database['public']['Tables']['app_settings']['Row']>
        Update: Partial<Database['public']['Tables']['app_settings']['Row']>
      }
      hostels: {
        Row: {
          id: string
          name: string
          description: string | null
          is_active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          description?: string | null
          is_active?: boolean
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['hostels']['Insert']>
      }
      hostel_students: {
        Row: {
          id: string
          name: string
          phone: string
          email: string | null
          dob: string | null
          course: string | null
          hostel_id: string | null
          room_number: string | null
          joining_date: string
          exit_date: string | null
          monthly_fee_amount: number
          fee_day: number
          override_due_date: string | null
          discount: number
          status: 'active' | 'exited'
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          phone: string
          email?: string | null
          dob?: string | null
          course?: string | null
          hostel_id?: string | null
          room_number?: string | null
          joining_date?: string
          exit_date?: string | null
          monthly_fee_amount?: number
          fee_day?: number
          override_due_date?: string | null
          discount?: number
          status?: 'active' | 'exited'
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['hostel_students']['Insert']>
      }
      hostel_fees: {
        Row: {
          id: string
          student_id: string
          month: number
          year: number
          due_date: string
          total_amount: number
          discount: number
          net_amount: number
          paid_amount: number
          balance: number
          status: 'pending' | 'partial' | 'paid' | 'overdue'
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          student_id: string
          month: number
          year: number
          due_date: string
          total_amount: number
          discount?: number
          net_amount: number
          paid_amount?: number
          status?: 'pending' | 'partial' | 'paid' | 'overdue'
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['hostel_fees']['Insert']>
      }
      library_members: {
        Row: {
          id: string
          name: string
          phone: string
          email: string | null
          dob: string | null
          seat_number: string | null
          joining_date: string
          exit_date: string | null
          monthly_fee_amount: number
          fee_day: number
          discount: number
          status: 'active' | 'exited'
          linked_hostel_id: string | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          phone: string
          email?: string | null
          dob?: string | null
          seat_number?: string | null
          joining_date?: string
          exit_date?: string | null
          monthly_fee_amount?: number
          fee_day?: number
          discount?: number
          status?: 'active' | 'exited'
          linked_hostel_id?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['library_members']['Insert']>
      }
      library_fees: {
        Row: {
          id: string
          member_id: string
          month: number
          year: number
          due_date: string
          total_amount: number
          discount: number
          net_amount: number
          paid_amount: number
          balance: number
          status: 'pending' | 'partial' | 'paid' | 'overdue'
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          member_id: string
          month: number
          year: number
          due_date: string
          total_amount: number
          discount?: number
          net_amount: number
          paid_amount?: number
          status?: 'pending' | 'partial' | 'paid' | 'overdue'
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['library_fees']['Insert']>
      }
      mess_members: {
        Row: {
          id: string
          name: string
          phone: string
          email: string | null
          meal_plan: 'veg' | 'non_veg' | 'custom'
          custom_plan_name: string | null
          joining_date: string
          exit_date: string | null
          monthly_fee_amount: number
          fee_day: number
          discount: number
          status: 'active' | 'exited'
          linked_hostel_id: string | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          phone: string
          email?: string | null
          meal_plan?: 'veg' | 'non_veg' | 'custom'
          custom_plan_name?: string | null
          joining_date?: string
          exit_date?: string | null
          monthly_fee_amount?: number
          fee_day?: number
          discount?: number
          status?: 'active' | 'exited'
          linked_hostel_id?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['mess_members']['Insert']>
      }
      mess_fees: {
        Row: {
          id: string
          member_id: string
          month: number
          year: number
          due_date: string
          total_amount: number
          discount: number
          net_amount: number
          paid_amount: number
          balance: number
          status: 'pending' | 'partial' | 'paid' | 'overdue'
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          member_id: string
          month: number
          year: number
          due_date: string
          total_amount: number
          discount?: number
          net_amount: number
          paid_amount?: number
          status?: 'pending' | 'partial' | 'paid' | 'overdue'
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['mess_fees']['Insert']>
      }
      complaints: {
        Row: {
          id: string
          student_id: string | null
          raised_by: string | null
          subject: string
          description: string
          priority: 'low' | 'medium' | 'high' | 'urgent'
          status: 'open' | 'in_progress' | 'resolved'
          resolution_note: string | null
          resolved_at: string | null
          resolved_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          student_id?: string | null
          raised_by?: string | null
          subject: string
          description: string
          priority?: 'low' | 'medium' | 'high' | 'urgent'
          status?: 'open' | 'in_progress' | 'resolved'
          resolution_note?: string | null
          resolved_at?: string | null
          resolved_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['complaints']['Insert']>
      }
      expenses: {
        Row: {
          id: string
          description: string
          amount: number
          category: 'maintenance' | 'utilities' | 'staff' | 'food' | 'misc' | 'other'
          expense_date: string
          notes: string | null
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          description: string
          amount: number
          category?: 'maintenance' | 'utilities' | 'staff' | 'food' | 'misc' | 'other'
          expense_date?: string
          notes?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['expenses']['Insert']>
      }
      leaves: {
        Row: {
          id: string
          student_id: string
          from_date: string
          to_date: string | null
          reason: string | null
          status: 'active' | 'ended'
          is_current: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          student_id: string
          from_date: string
          to_date?: string | null
          reason?: string | null
          status?: 'active' | 'ended'
          is_current?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['leaves']['Insert']>
      }
      deleted_records: {
        Row: {
          id: string
          table_name: string
          record_id: string
          record_data: Json
          deleted_by: string | null
          deleted_at: string
        }
        Insert: {
          id?: string
          table_name: string
          record_id: string
          record_data: Json
          deleted_by?: string | null
          deleted_at?: string
        }
        Update: Partial<Database['public']['Tables']['deleted_records']['Insert']>
      }
      payment_log: {
        Row: {
          id: string
          module: 'hostel' | 'library' | 'mess'
          fee_id: string
          member_id: string
          amount: number
          mode: 'cash' | 'upi' | 'cheque' | 'bank_transfer' | 'other'
          notes: string | null
          paid_at: string
          created_by: string | null
        }
        Insert: {
          id?: string
          module: 'hostel' | 'library' | 'mess'
          fee_id: string
          member_id: string
          amount: number
          mode?: 'cash' | 'upi' | 'cheque' | 'bank_transfer' | 'other'
          notes?: string | null
          paid_at?: string
          created_by?: string | null
        }
        Update: Partial<Database['public']['Tables']['payment_log']['Insert']>
      }
      rooms: {
        Row: {
          id: string
          hostel_id: string
          room_number: string
          capacity: number
          is_active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          hostel_id: string
          room_number: string
          capacity?: number
          is_active?: boolean
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['rooms']['Insert']>
      }
      mess_attendance: {
        Row: {
          id: string
          member_id: string
          att_date: string
          present: boolean
          created_at: string
        }
        Insert: {
          id?: string
          member_id: string
          att_date: string
          present?: boolean
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['mess_attendance']['Insert']>
      }
      broadcast_log: {
        Row: {
          id: string
          subject: string
          message: string
          target: 'all' | 'hostel' | 'library' | 'mess'
          sent_by: string | null
          created_at: string
        }
        Insert: {
          id?: string
          subject: string
          message: string
          target?: 'all' | 'hostel' | 'library' | 'mess'
          sent_by?: string | null
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['broadcast_log']['Insert']>
      }
    }
    Views: {}
    Functions: {
      current_user_role: {
        Args: {}
        Returns: string
      }
      current_student_id: {
        Args: {}
        Returns: string
      }
    }
    Enums: {}
  }
}
